### PR TITLE
Controller/Component Resilience for better UX 

### PR DESCRIPTION
**Pull request by elnicko**
Hi Frank,
please take a look at these changes. I also added a use-case in the wiki.
Kind regards, Nick

### CODE REVIEW

**Comment by TDesjardins** [comment]
Hi @elnicko, your approach only works when using the same route right? If you switch between two cached controllers the status of dom elements will still get lost (scrollbar positions, stateful content like an iframe or a video etc.). I posted another[ approach](https://github.com/NaluKit/nalu/issues/114) for a while for solving this issue which should work in both cases: https://github.com/NaluKit/nalu/issues/114
WDYT?

**Comment by elnicko** [comment]
Hi @TDesjardins, I read the HTMLElement/hidden documentation link you provided. It appears to be spot on for the purpose of not losing UI state. Especially since it appears to cover also the corner case you described, which my proposed solution does not.

What I'm not 100% sure about yet is whether Nalu should _always_ preserve the full state for cached controllers, or are there cases, in which the developer would like to choose between preserving or replacing the US state. I can think of cases of both types but I cannot assess their importance. I guess it is depending on the context of the developers themselves. That's why I feel that it is appropriate for this feature to be configurable with default behavior targeting the largest group of people.

**Comment by TDesjardins** [comment]
> That's why I feel that it is appropriate for this feature to be configurable with default behavior targeting the largest group of people. What do you think?

Yes, this behaviour should be configurable. Maybe the hidden part has also some impact in terms of performance if all your pages stay in the DOM.
Regarding the default behaviour I also can't say which kind of behaviour will be the most used/expected by the developers. Maybe we should leave the current behaviour as default for backwards compatibility but if the hidden approach works fine I would prefer this as default.

P.S. Thanks for the good explanation of your issue!

**Comment by elnicko** [comment]
I agree. Configurability and backward compatibility sounds like the way to go.

PS: sure, I'm glad to be of help. Thanks for responding so quickly and taking a closer look at my proposed changes.

**Pull request merged**
