### PR TITLE
Update Elemental2: v1.0.0-rc1 -> v1.0.0

### PR DESCRIPTION
**Pull request by factuno-db**
Methods on `Location` were changed to fields.

### CODE REVIEW

**Comment by FrankHossfeld** [comment]
Thanks for contributing Nalu!

But, I think, bad news, we have to wait until GWT 2.9 is shipped. 
See: https://gitter.im/gwtproject/gwt?at=5d8929da5ab9361694456661 for more informations. 

Think, we shpuld wait until GWT 2.9 is shipped and it is clear, that the update path is simple. Otherwise we would avoid Nalu user using the new Nalu version.

**Comment by factuno-db** [comment]
Corrected several spelling mistakes. Hope this doesn't break anything!

**Comment by FrankHossfeld** [comment]
Awesome!

**Comment by factuno-db** [comment]
> But, I think, bad news, we have to wait until GWT 2.9 is shipped.
> See: https://gitter.im/gwtproject/gwt?at=5d8929da5ab9361694456661 for more informations.

Alright, so I'm closing this issue for now.

**Pull request closed without merging**
