### PR TITLE
Upgrade to Elemento 1.0.0-rc1

### PR DESCRIPTION
**Pull request by hpehl**
Upgrade Elemento to 1.0.0-rc1

### CODE REVIEW

**Comment by hpehl** [comment]
I've not tested whether the upgrade works. Elelemto 1.0.0 depends on Elemental2 1.0.0, whereas Nalu depends on Elemental2 1.0.0.RC1.

**Comment by FrankHossfeld** [comment]
I think, we will ran into problems. `nalu-plugin-core-web` adds a dependency to elemental2. This module is used by all other plugin modules. So, yes, I think, we will have version problems. 

In my opinion, the only workable solution for the time GWT 2.9 is not released, is to create a separate branch for Elemental2 v1.0.0. So, we are able to use Nalu with GWT 2.8 and with the current trunk and the amount of work is not so much to handle both branches.

What do you think?

**Comment by ibaca** [comment]
But, you can use elemento with elemental2 rc1, just need to define each elemental2 dependency in your project, so it overrides the elemento one. I have tested and it works.

**Comment by FrankHossfeld** [comment]
@ibaca Did you test it with Nalu?

Mmmh, if it works, it would be a perfect solution.

**Comment by ibaca** [comment]
No, I don't test it with Nalu,  I actually tested elemento itself, I forced to compile elemento and its GWT sample with elemental2 rc1 and it works, so I suppose there is no reason to not to work in other cases.

**Comment by hpehl** [comment]
Sounds good to me. I leave it to you @FrankHossfeld to merge the PR or create a separate branch for it.

**Comment by FrankHossfeld** [comment]
Agree. Will merge and try to make in work in one branch. If I ran into problems, I'll create a second branch (fallback solution).

Think, I'll find some time later.

**Pull request merged**
